test_file: '/data/data/covid_rural/test.csv'
disease_book: 'observation explanation.json'

dataset: 'covid-r'
root: '/data/data/covid_rural'
target: 'covid19'
model_path: ../Pretrain/data_file/MedKLIP/checkpoint_final.pth

image_res: 224
test_batch_size: 256

model: medklip
d_model: 256
res_base_model: 'resnet50'
decoder: cross
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
pretrained: True



