train_file: 'Pretrain/data_file/MedKLIP/rad_graph_metric_train.json'
valid_file: 'Pretrain/data_file/MedKLIP/rad_graph_metric_validate.json'
test_file: 'Pretrain/data_file/MedKLIP/rad_graph_metric_test.json'
label_file: 'Pretrain/data_file/MedKLIP/landmark_observation_adj_mtx.npy'
disease_book: 'Pretrain/data_file/observation explanation.json'
concept_book: 'Pretrain/concept_gen/gpt4_mimic.json'

image_res: 224
patch_size: 16
num_sentences: 12
num_tokens: 32
vision_width: 768
fea_width: 197
embed_dim: 256
batch_size: 128
test_batch_size: 128

