train_file: '/data/data/xray14/official_train.csv'
valid_file: '/data/data/xray14/official_valid.csv'
test_file: '/data/data/xray14/official_test.csv'
root: '/data/data/xray14/cxr'
dataset: 'chexray'
pretrain: ../../Pretrain/data_file/MedKLIP/checkpoint_final.pth
model_path: output_chexray_medklip_100/best_valid.pth

model: 'medklip'
image_res: 224
batch_size: 256
test_batch_size: 256
temp: 0.07
mlm_probability: 0.15
queue_size: 8192
momentum: 0.995
alpha: 0.4
data_pct: 1.0

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 60, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}
