test_file: '/data/data/xray14/test.csv'
disease_book: 'observation explanation.json'
concept_book: '../Pretrain/concept_gen/gpt4_mimic.json'

dataset: 'chexray'
root: '/data/data/xray14/cxr'
model: mavl
#model_path: '../checkpoints/cl_global_1e-1_true/checkpoint_34.pth'
model_path: '../checkpoints/cl_global_1e-1_clean/checkpoint_40.pth'

image_res: 224
test_batch_size: 512

d_model: 256
base_model: 'resnet50'
decoder: cross
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4
self_attention: True
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
pretrained: True
mode: feature