test_file: '/data/data/chexpertv1/CheXpert-v1.0/filter_test_labels.csv'
disease_book: 'observation explanation.json'
concept_book: '../Pretrain/concept_gen/gpt4_mimic.json'

dataset: 'chexpert'
root: '/data/data/chexpertv1'
model: 'mavl'
model_path: '../checkpoints/checkpoint_40.pth'
mode: feature

image_res: 224
test_batch_size: 256

d_model: 256
base_model: 'resnet50'
decoder: cross
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
self_attention: True
pretrained: True
chexpert_subset: True
