test_file: '/data/VLM/data/covidx-cxr2/test_split.csv'
disease_book: 'observation explanation.json'
concept_book: '../Pretrain/concept_gen/gpt3_mimic_important_chest.json'

dataset: 'covid-cxr2'
root: '/data/VLM/data/covidx-cxr2/train'
model: 'medklip'
model_path: '../Pretrain/data_file/MedKLIP/checkpoint_final.pth'

image_res: 224
test_batch_size: 256

d_model: 256
res_base_model: 'resnet50'
decoder: cross
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
