test_file: '../data/padchest/test.csv'
disease_book: 'observation explanation_padchest_rare.json'
# concept_book: '../Pretrain/concept_gen/gpt4_mimic_padchest_rare.json'
concept_book: '../Pretrain/concept_gen/gpt4_mimic_padchest_rare.json'

dataset: 'padchest'
root: '/data2/PadChest/'
model: 'mavl'
model_path: '../checkpoints/checkpoint_full_46.pth'

image_res: 224
test_batch_size: 512

d_model: 256
base_model: 'resnet50'
decoder: cross
num_queries: 75
dropout: 0.1
attribute_set_size: 2
N: 4
H: 4
text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
self_attention: True
pretrained: True
mode: text
class: rare